# Generated by Django 6.0.4 on 2026-04-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('return', 'Return')], default='sale', max_length=10),
        ),
    ]
